CREATE TABLE role (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    label VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE user (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);

CREATE TABLE category (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    label VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE seed (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    label VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE sowing (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    month TINYINT UNSIGNED NOT NULL CHECK (month BETWEEN 1 AND 12),
    seed_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (seed_id) REFERENCES seed(id) ON DELETE CASCADE
);

CREATE TABLE harvest (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    month TINYINT UNSIGNED NOT NULL CHECK (month BETWEEN 1 AND 12),
    seed_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (seed_id) REFERENCES seed(id) ON DELETE CASCADE
);
